# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  tags:
    include:
    - v*
  branches:
    include:
    - master

variables:
  vmImageOfBuild: windows-2019
  buildConfiguration: Release
  buildProject: KJlib.Kihon.Core/KJlib.Kihon.Core.csproj
  testProjects: KJlib.Kihon.Tests/**/*.csproj

stages:
- stage: build_test_stage
##  condition: in(variables['Build.Reason'], 'PullRequest', 'Manual')
  jobs:
  - job: test_job
    displayName: Test
    pool:
      vmImage: $(vmImageOfBuild)
    steps:
    - task: DotNetCoreCLI@2
      displayName: Test
      inputs:
        command: 'test'
        projects: $(testProjects)
        testRunTitle: 'run tests'

- stage: individual_ci_stage
##  condition: eq(variables['Build.Reason'], 'IndividualCI')
  jobs:
  - job: logging
    pool:
      vmImage: $(vmImageOfBuild)
    steps:
    - script: |
        echo master branch recieved Git-push.
        echo Build.Reason is $(Build.Reason)
        echo Build.SourceBranch is $(Build.SourceBranch)
- stage: push_stage
##  condition: startsWith(variables['Build.SourceBranch'], 'refs/tags/v')
  condition: startsWith(variables['Build.SourceBranch'], 'refs/heads/master')
  jobs:
  - job: pack_job
    displayName: Pack and Push
    pool:
      vmImage: $(vmImageOfBuild)
    steps:
    - task: DotNetCoreCLI@2
      displayName: 'DotNetCoreCLI@2: build'
      inputs:
        command: 'build'
        projects: '$(buildProject)'
        arguments: '--configuration $(buildConfiguration)'
    - task: DotNetCoreCLI@2
      displayName: 'DotNetCoreCLI@2: pack'
      inputs:
        command: 'pack'
        packagesToPack: '$(buildProject)'
        configuration: '$(buildConfiguration)'
        nobuild: true
        versioningScheme: 'off'
    - task: DotNetCoreCLI@2
      displayName: 'DotNetCoreCLI@2: push'
      inputs:
        command: 'push'
        packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
        nuGetFeedType: 'internal'
        publishVstsFeed: '63faa203-4652-4c9d-b760-c516955ac348/a37dfd0f-e52c-4183-a9d7-6f25b552e029'
