name: Publish - Nuget

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  TargetProjectPath: .\KJlib.Kihon.Core\KJlib.Kihon.Core.csproj
  TestProjectPath: .\KJlib.Kihon.Tests\KJlib.Kihon.Tests.csproj
  NUGET_URL: https://nuget.pkg.github.com/kjsystems/index.json

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        dotnet-version: ['6.0.x', '9.0.x']
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET ${{ matrix.dotnet-version }}
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ matrix.dotnet-version }}
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration Release
    - name: Test
      run: dotnet test ${{env.TestProjectPath}}

  package-and-publish:
    runs-on: windows-latest
    permissions:
      packages: write
    needs: build
    if: github.ref == 'refs/heads/master' && github.event_name == 'push'
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET 6.0.x for packaging
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '6.0.x'
    - name: Restore dependencies
      run: dotnet restore
    - name: Build for packaging
      run: dotnet build --no-restore --configuration Release
    - name: Pack
      run: dotnet pack ${{env.TargetProjectPath}} --output .\artifacts --configuration Release
    - name: Ensure GitHub NuGet Source
      run: dotnet nuget add source ${{env.NUGET_URL}} --name github --username masatoru --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text
    - name: Publish NuGet Package
      run: dotnet nuget push .\artifacts\*.nupkg --source github --skip-duplicate --api-key ${{ secrets.GITHUB_TOKEN }}
    - name: Publish to NuGet.org (manual)
      env:
        NUGET_KEY: ${{ secrets.NUGET_API_KEY }}
      run: |
        echo "Publishing packages to NuGet.org"
        if [ -z "%NUGET_KEY%" ]; then
          echo "##[error] NUGET_API_KEY secret is not set"
          exit 1
        fi
        dotnet nuget push .\artifacts\*.nupkg -s https://api.nuget.org/v3/index.json -k %NUGET_KEY% --skip-duplicate