name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  TargetProjectPath: .\KJlib.Kihon.Core\KJlib.Kihon.Core.csproj
  TestProjectPath: .\KJlib.Kihon.Tests\KJlib.Kihon.Tests.csproj
  NUGET_URL: https://nuget.pkg.github.com/kjsystems/index.json

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration Release
    - name: Test
      run: dotnet test ${{env.TestProjectPath}}
    - name: Pack
      run: dotnet pack ${{env.TargetProjectPath}} |
        --output .\artifacts |
        --configuration Release
    - name: Ensure GitHub NuGet Source
      run: dotnet nuget add source ${{env.NUGET_URL}} |
        --name github |
        --username masatoru |
        --password ${{ secrets.GITHUB_TOKEN }} |
        --store-password-in-clear-text
    - name: Publish NuGet Package
      run: dotnet nuget push .\artifacts\*.nupkg |
        --source github |
        --skip-duplicate